services:
  - type: web
    name: paddy-disease-prediction
    env: python
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y git-lfs
      git lfs install
      git lfs pull
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn crop.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: crop.settings
      - key: "django-insecure-35@71%w5t$0htprbxks_657*a(z3%ugw6g3@zcf3227s8^_=mg"
        sync: false
      - key: ALLOWED_HOSTS
        value: "paddy_disease_predictor1.onrender.com"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
