services:
  - type: web
    name: paddy-disease-prediction
    env: python
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y git-lfs
      git lfs install
      git lfs pull
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn your_project_name.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: "paddy-disease-predictor1.onrender.com"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
