services:
  - type: web
    name: paddy-disease-prediction
    env: python
    region: oregon # or adjust based on your region
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn crop.wsgi:application
    autoDeploy: true
    envVars:
      - key: "django-insecure-35@71%w5t$0htprbxks_657*a(z3%ugw6g3@zcf3227s8^_=mg"
        sync: false
      - key: ALLOWED_HOSTS
        value: " ['127.0.0.1', 'localhost', 'paddy_disease_predictor.onrender.com'] "
      - key: DATABASE_URL
        sync: false 
      - key: DEBUG
        value: "False"
